import { readFileSync, writeFileSync } from "fs";

import { CONFIG } from "./config.mjs";

const DEMO_DATA_MARKER = "const PRODUCT_SEEDS: ProductSeed[] = [";

function escapeSqlString(value) {
  return String(value ?? "").replace(/'/g, "''");
}

function loadProductIdBySlug() {
  const source = readFileSync(CONFIG.paths.demoData, "utf8");
  const start = source.indexOf(DEMO_DATA_MARKER);
  if (start < 0) throw new Error("Could not find PRODUCT_SEEDS in demo-data.ts");

  const block = source.slice(start);
  const matches = [...block.matchAll(/id: "(a1000000-[^"]+)",\s*\n\s*slug: "([^"]+)"/g)];
  const map = new Map();
  for (const [, id, slug] of matches) {
    map.set(slug, id);
  }
  return map;
}

function mediaIdForProduct(productId, index) {
  return `d1000000-0000-4000-8000-${productId.slice(-12)}${String(index + 1).padStart(2, "0")}`;
}

export function buildProductMediaSeedSql(manifest) {
  const productIdBySlug = loadProductIdBySlug();
  const rows = [];
  const slugs = [];

  for (const product of manifest.products) {
    const productId = productIdBySlug.get(product.slug);
    if (!productId || !product.media?.length) continue;

    slugs.push(product.slug);
    for (const [index, entry] of product.media.entries()) {
      rows.push({
        id: mediaIdForProduct(productId, index),
        productId,
        mediaType: entry.mediaType,
        url: entry.url,
        altText: entry.altText ?? product.title,
        sortOrder: entry.sortOrder ?? index + 1,
        isPrimary: Boolean(entry.isPrimary),
      });
    }
  }

  if (!rows.length) {
    throw new Error("No product media rows generated — check demo-data slug map and manifest media entries");
  }

  const slugList = slugs.map((slug) => `'${escapeSqlString(slug)}'`).join(", ");
  const values = rows
    .map(
      (row) =>
        `  ('${row.id}', '${row.productId}', '${row.mediaType}', '${escapeSqlString(row.url)}', '${escapeSqlString(row.altText)}', ${row.sortOrder}, ${row.isPrimary})`,
    )
    .join(",\n");

  return `-- Auto-generated by waydoo-media-importer at ${manifest.generatedAt}
-- Imported product media for ${slugs.length} catalog products (${rows.length} rows).
-- Run after store/supabase/seed/001_waydoo_catalog.sql

BEGIN;

DELETE FROM public.product_media
WHERE product_id IN (
  SELECT id FROM public.products WHERE slug IN (${slugList})
);

INSERT INTO public.product_media (id, product_id, media_type, url, alt_text, sort_order, is_primary)
VALUES
${values}
ON CONFLICT (id) DO UPDATE SET
  product_id = EXCLUDED.product_id,
  media_type = EXCLUDED.media_type,
  url = EXCLUDED.url,
  alt_text = EXCLUDED.alt_text,
  sort_order = EXCLUDED.sort_order,
  is_primary = EXCLUDED.is_primary;

COMMIT;
`;
}

export function writeProductMediaSeedFile(manifest, logger) {
  const sql = buildProductMediaSeedSql(manifest);
  const outputPath = CONFIG.paths.productMediaSeedSql;
  writeFileSync(outputPath, sql);
  const productCount = new Set(
    manifest.products.filter((product) => product.media?.length).map((product) => product.slug),
  ).size;
  logger.info(`Wrote product media seed (${productCount} products) to ${outputPath}`);
}
